apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phatodo
  namespace: phatodo
spec:
  ingressClassName: traefik
  rules:
    - host: todo.phat.wtf
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: phatodo-server
                port:
                  name: http
