// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
	"time"
)

const historyEvents = `-- name: HistoryEvents :many
SELECT id, workspace_id, project_id, action, entity_type, entity_id, actor_user_id, actor_label, before_state, after_state, metadata, created_at
FROM events
WHERE project_id = $1
  AND ($2 = '' OR entity_id = $2)
  AND ($3 = '' OR entity_type = $3)
  AND ($4 = '' OR action = $4)
  AND ($5 IS NULL OR created_at >= $5)
ORDER BY created_at DESC, id DESC
LIMIT $6
`

type HistoryEventsParams struct {
	ProjectID  string      `json:"project_id"`
	EntityID   interface{} `json:"entity_id"`
	EntityType interface{} `json:"entity_type"`
	Action     interface{} `json:"action"`
	Since      interface{} `json:"since"`
	QueryLimit int32       `json:"query_limit"`
}

func (q *Queries) HistoryEvents(ctx context.Context, arg HistoryEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, historyEvents,
		arg.ProjectID,
		arg.EntityID,
		arg.EntityType,
		arg.Action,
		arg.Since,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.ActorUserID,
			&i.ActorLabel,
			&i.BeforeState,
			&i.AfterState,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events (
	workspace_id, project_id, action, entity_type, entity_id,
	actor_user_id, actor_label, before_state, after_state, metadata
) VALUES (
	$1, $2, $3, $4, $5,
	NULLIF($6, ''), NULLIF($7, ''),
	$8::jsonb, $9::jsonb, COALESCE($10::jsonb, '{}'::jsonb)
)
`

type InsertEventParams struct {
	WorkspaceID string      `json:"workspace_id"`
	ProjectID   string      `json:"project_id"`
	Action      string      `json:"action"`
	EntityType  string      `json:"entity_type"`
	EntityID    string      `json:"entity_id"`
	ActorUserID interface{} `json:"actor_user_id"`
	ActorLabel  interface{} `json:"actor_label"`
	BeforeState []byte      `json:"before_state"`
	AfterState  []byte      `json:"after_state"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.Exec(ctx, insertEvent,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.ActorUserID,
		arg.ActorLabel,
		arg.BeforeState,
		arg.AfterState,
		arg.Metadata,
	)
	return err
}

const listTasksUnified = `-- name: ListTasksUnified :many
SELECT id, title, COALESCE(description, ''), status, priority, epic_id, parent_task_id, tags, created_at, updated_at
FROM tasks
WHERE project_id = $1
  AND ($2 = '' OR status = $2)
ORDER BY created_at ASC, id ASC
`

type ListTasksUnifiedParams struct {
	ProjectID string      `json:"project_id"`
	Status    interface{} `json:"status"`
}

type ListTasksUnifiedRow struct {
	ID           string    `json:"id"`
	Title        string    `json:"title"`
	Description  string    `json:"description"`
	Status       string    `json:"status"`
	Priority     int32     `json:"priority"`
	EpicID       *string   `json:"epic_id"`
	ParentTaskID *string   `json:"parent_task_id"`
	Tags         []string  `json:"tags"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) ListTasksUnified(ctx context.Context, arg ListTasksUnifiedParams) ([]ListTasksUnifiedRow, error) {
	rows, err := q.db.Query(ctx, listTasksUnified, arg.ProjectID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTasksUnifiedRow{}
	for rows.Next() {
		var i ListTasksUnifiedRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.EpicID,
			&i.ParentTaskID,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchComments = `-- name: SearchComments :many
SELECT id, author, kind, content, created_at, updated_at, task_id
FROM comments
WHERE project_id = $1
  AND (
	LOWER(id) LIKE '%' || LOWER($2) || '%'
	OR LOWER(author) LIKE '%' || LOWER($2) || '%'
	OR LOWER(kind) LIKE '%' || LOWER($2) || '%'
	OR LOWER(content) LIKE '%' || LOWER($2) || '%'
  )
ORDER BY created_at DESC, id ASC
`

type SearchCommentsParams struct {
	ProjectID string `json:"project_id"`
	Query     string `json:"query"`
}

type SearchCommentsRow struct {
	ID        string    `json:"id"`
	Author    string    `json:"author"`
	Kind      string    `json:"kind"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	TaskID    string    `json:"task_id"`
}

func (q *Queries) SearchComments(ctx context.Context, arg SearchCommentsParams) ([]SearchCommentsRow, error) {
	rows, err := q.db.Query(ctx, searchComments, arg.ProjectID, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchCommentsRow{}
	for rows.Next() {
		var i SearchCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Author,
			&i.Kind,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TaskID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchEpics = `-- name: SearchEpics :many
SELECT id, title, COALESCE(description, ''), status, priority, created_at, updated_at
FROM epics
WHERE project_id = $1
  AND ($2 = '' OR status = $2)
  AND (
	LOWER(id) LIKE '%' || LOWER($3) || '%'
	OR LOWER(title) LIKE '%' || LOWER($3) || '%'
	OR LOWER(COALESCE(description, '')) LIKE '%' || LOWER($3) || '%'
  )
ORDER BY created_at DESC, id ASC
`

type SearchEpicsParams struct {
	ProjectID string      `json:"project_id"`
	Status    interface{} `json:"status"`
	Query     string      `json:"query"`
}

type SearchEpicsRow struct {
	ID          string    `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Status      string    `json:"status"`
	Priority    int32     `json:"priority"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) SearchEpics(ctx context.Context, arg SearchEpicsParams) ([]SearchEpicsRow, error) {
	rows, err := q.db.Query(ctx, searchEpics, arg.ProjectID, arg.Status, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchEpicsRow{}
	for rows.Next() {
		var i SearchEpicsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTasks = `-- name: SearchTasks :many
SELECT id, title, COALESCE(description, ''), status, priority, epic_id, parent_task_id, created_at, updated_at
FROM tasks
WHERE project_id = $1
  AND ($2 = '' OR status = $2)
  AND (
	LOWER(id) LIKE '%' || LOWER($3) || '%'
	OR LOWER(title) LIKE '%' || LOWER($3) || '%'
	OR LOWER(COALESCE(description, '')) LIKE '%' || LOWER($3) || '%'
  )
ORDER BY created_at DESC, id ASC
`

type SearchTasksParams struct {
	ProjectID string      `json:"project_id"`
	Status    interface{} `json:"status"`
	Query     string      `json:"query"`
}

type SearchTasksRow struct {
	ID           string    `json:"id"`
	Title        string    `json:"title"`
	Description  string    `json:"description"`
	Status       string    `json:"status"`
	Priority     int32     `json:"priority"`
	EpicID       *string   `json:"epic_id"`
	ParentTaskID *string   `json:"parent_task_id"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) SearchTasks(ctx context.Context, arg SearchTasksParams) ([]SearchTasksRow, error) {
	rows, err := q.db.Query(ctx, searchTasks, arg.ProjectID, arg.Status, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchTasksRow{}
	for rows.Next() {
		var i SearchTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.EpicID,
			&i.ParentTaskID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
