// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bootstrap.sql

package db

import (
	"context"
)

const countAdminUsers = `-- name: CountAdminUsers :one
SELECT COUNT(*)::bigint
FROM users
WHERE role = 'admin'
`

func (q *Queries) CountAdminUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminUsers)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, workspace_id, name)
VALUES ($1, $2, $3)
ON CONFLICT (workspace_id, name) DO NOTHING
RETURNING id
`

type CreateProjectParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	Name        string `json:"name"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (string, error) {
	row := q.db.QueryRow(ctx, createProject, arg.ID, arg.WorkspaceID, arg.Name)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (id, name, slug)
VALUES ($1, $2, $3)
ON CONFLICT (slug) DO NOTHING
RETURNING id
`

type CreateWorkspaceParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (string, error) {
	row := q.db.QueryRow(ctx, createWorkspace, arg.ID, arg.Name, arg.Slug)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getProjectIDByWorkspaceAndName = `-- name: GetProjectIDByWorkspaceAndName :one
SELECT id
FROM projects
WHERE workspace_id = $1 AND name = $2
LIMIT 1
`

type GetProjectIDByWorkspaceAndNameParams struct {
	WorkspaceID string `json:"workspace_id"`
	Name        string `json:"name"`
}

func (q *Queries) GetProjectIDByWorkspaceAndName(ctx context.Context, arg GetProjectIDByWorkspaceAndNameParams) (string, error) {
	row := q.db.QueryRow(ctx, getProjectIDByWorkspaceAndName, arg.WorkspaceID, arg.Name)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getWorkspaceIDBySlug = `-- name: GetWorkspaceIDBySlug :one
SELECT id
FROM workspaces
WHERE slug = $1
LIMIT 1
`

func (q *Queries) GetWorkspaceIDBySlug(ctx context.Context, slug string) (string, error) {
	row := q.db.QueryRow(ctx, getWorkspaceIDBySlug, slug)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertAdminUser = `-- name: InsertAdminUser :exec
INSERT INTO users (
	id, display_name, role, access_key, access_secret_hash,
	username, password_hash
) VALUES (
	$1, $2, 'admin', $3, $4,
	$5, $6
)
`

type InsertAdminUserParams struct {
	ID               string  `json:"id"`
	DisplayName      string  `json:"display_name"`
	AccessKey        string  `json:"access_key"`
	AccessSecretHash string  `json:"access_secret_hash"`
	Username         *string `json:"username"`
	PasswordHash     *string `json:"password_hash"`
}

func (q *Queries) InsertAdminUser(ctx context.Context, arg InsertAdminUserParams) error {
	_, err := q.db.Exec(ctx, insertAdminUser,
		arg.ID,
		arg.DisplayName,
		arg.AccessKey,
		arg.AccessSecretHash,
		arg.Username,
		arg.PasswordHash,
	)
	return err
}

const insertBootstrapUser = `-- name: InsertBootstrapUser :exec
INSERT INTO users (
	id, display_name, role, access_key, access_secret_hash
) VALUES (
	$1, $2, 'user', $3, $4
)
`

type InsertBootstrapUserParams struct {
	ID               string `json:"id"`
	DisplayName      string `json:"display_name"`
	AccessKey        string `json:"access_key"`
	AccessSecretHash string `json:"access_secret_hash"`
}

func (q *Queries) InsertBootstrapUser(ctx context.Context, arg InsertBootstrapUserParams) error {
	_, err := q.db.Exec(ctx, insertBootstrapUser,
		arg.ID,
		arg.DisplayName,
		arg.AccessKey,
		arg.AccessSecretHash,
	)
	return err
}

const insertUserProjectAccess = `-- name: InsertUserProjectAccess :exec
INSERT INTO user_project_access (
	user_id, workspace_id, project_id
) VALUES (
	$1, $2, $3
)
`

type InsertUserProjectAccessParams struct {
	UserID      string `json:"user_id"`
	WorkspaceID string `json:"workspace_id"`
	ProjectID   string `json:"project_id"`
}

func (q *Queries) InsertUserProjectAccess(ctx context.Context, arg InsertUserProjectAccessParams) error {
	_, err := q.db.Exec(ctx, insertUserProjectAccess, arg.UserID, arg.WorkspaceID, arg.ProjectID)
	return err
}

const lockUsersTable = `-- name: LockUsersTable :exec
LOCK TABLE users IN SHARE ROW EXCLUSIVE MODE
`

func (q *Queries) LockUsersTable(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockUsersTable)
	return err
}

const lookupAdminByUsername = `-- name: LookupAdminByUsername :one
SELECT id, display_name, role, access_key, access_secret_hash, username, password_hash
FROM users
WHERE username = $1 AND role = 'admin'
LIMIT 1
`

type LookupAdminByUsernameRow struct {
	ID               string  `json:"id"`
	DisplayName      string  `json:"display_name"`
	Role             string  `json:"role"`
	AccessKey        string  `json:"access_key"`
	AccessSecretHash string  `json:"access_secret_hash"`
	Username         *string `json:"username"`
	PasswordHash     *string `json:"password_hash"`
}

func (q *Queries) LookupAdminByUsername(ctx context.Context, username *string) (LookupAdminByUsernameRow, error) {
	row := q.db.QueryRow(ctx, lookupAdminByUsername, username)
	var i LookupAdminByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Role,
		&i.AccessKey,
		&i.AccessSecretHash,
		&i.Username,
		&i.PasswordHash,
	)
	return i, err
}

const lookupUserByAccessKey = `-- name: LookupUserByAccessKey :one
SELECT id, display_name, role, access_key, access_secret_hash, username, password_hash, disabled_at, last_seen_at, created_at, updated_at
FROM users
WHERE access_key = $1
LIMIT 1
`

func (q *Queries) LookupUserByAccessKey(ctx context.Context, accessKey string) (User, error) {
	row := q.db.QueryRow(ctx, lookupUserByAccessKey, accessKey)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Role,
		&i.AccessKey,
		&i.AccessSecretHash,
		&i.Username,
		&i.PasswordHash,
		&i.DisabledAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
