// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package db

import (
	"context"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (
	id, workspace_id, project_id, task_id, author_user_id, author, kind, content
) VALUES (
	$1, $2, $3, $4, NULLIF($5, ''),
	$6, $7, $8
)
RETURNING id, workspace_id, project_id, task_id, author_user_id, author, kind, content, created_at, updated_at
`

type CreateCommentParams struct {
	ID           string      `json:"id"`
	WorkspaceID  string      `json:"workspace_id"`
	ProjectID    string      `json:"project_id"`
	TaskID       string      `json:"task_id"`
	AuthorUserID interface{} `json:"author_user_id"`
	Author       string      `json:"author"`
	Kind         string      `json:"kind"`
	Content      string      `json:"content"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.ID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.TaskID,
		arg.AuthorUserID,
		arg.Author,
		arg.Kind,
		arg.Content,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.TaskID,
		&i.AuthorUserID,
		&i.Author,
		&i.Kind,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :one
DELETE FROM comments
WHERE project_id = $1 AND id = $2
RETURNING id, workspace_id, project_id, task_id, author_user_id, author, kind, content, created_at, updated_at
`

type DeleteCommentParams struct {
	ProjectID string `json:"project_id"`
	CommentID string `json:"comment_id"`
}

func (q *Queries) DeleteComment(ctx context.Context, arg DeleteCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, deleteComment, arg.ProjectID, arg.CommentID)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.TaskID,
		&i.AuthorUserID,
		&i.Author,
		&i.Kind,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getComment = `-- name: GetComment :one
SELECT id, workspace_id, project_id, task_id, author_user_id, author, kind, content, created_at, updated_at
FROM comments
WHERE project_id = $1 AND id = $2
LIMIT 1
`

type GetCommentParams struct {
	ProjectID string `json:"project_id"`
	CommentID string `json:"comment_id"`
}

func (q *Queries) GetComment(ctx context.Context, arg GetCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, getComment, arg.ProjectID, arg.CommentID)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.TaskID,
		&i.AuthorUserID,
		&i.Author,
		&i.Kind,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listComments = `-- name: ListComments :many
SELECT id, workspace_id, project_id, task_id, author_user_id, author, kind, content, created_at, updated_at
FROM comments
WHERE project_id = $1 AND task_id = $2
ORDER BY created_at ASC, id ASC
`

type ListCommentsParams struct {
	ProjectID string `json:"project_id"`
	TaskID    string `json:"task_id"`
}

func (q *Queries) ListComments(ctx context.Context, arg ListCommentsParams) ([]Comment, error) {
	rows, err := q.db.Query(ctx, listComments, arg.ProjectID, arg.TaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.TaskID,
			&i.AuthorUserID,
			&i.Author,
			&i.Kind,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComment = `-- name: UpdateComment :one
UPDATE comments
SET content = $1,
	updated_at = now()
WHERE project_id = $2 AND id = $3
RETURNING id, workspace_id, project_id, task_id, author_user_id, author, kind, content, created_at, updated_at
`

type UpdateCommentParams struct {
	Content   string `json:"content"`
	ProjectID string `json:"project_id"`
	CommentID string `json:"comment_id"`
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, updateComment, arg.Content, arg.ProjectID, arg.CommentID)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.TaskID,
		&i.AuthorUserID,
		&i.Author,
		&i.Kind,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
