// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dependencies.sql

package db

import (
	"context"
)

const createDependency = `-- name: CreateDependency :one
INSERT INTO dependencies (
	id, workspace_id, project_id, task_id, depends_on_id
) VALUES (
	$1, $2, $3, $4, $5
)
RETURNING id, workspace_id, project_id, task_id, depends_on_id, created_at
`

type CreateDependencyParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	ProjectID   string `json:"project_id"`
	TaskID      string `json:"task_id"`
	DependsOnID string `json:"depends_on_id"`
}

func (q *Queries) CreateDependency(ctx context.Context, arg CreateDependencyParams) (Dependency, error) {
	row := q.db.QueryRow(ctx, createDependency,
		arg.ID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.TaskID,
		arg.DependsOnID,
	)
	var i Dependency
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.TaskID,
		&i.DependsOnID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDependency = `-- name: DeleteDependency :one
DELETE FROM dependencies
WHERE project_id = $1 AND task_id = $2 AND depends_on_id = $3
RETURNING id, workspace_id, project_id, task_id, depends_on_id, created_at
`

type DeleteDependencyParams struct {
	ProjectID   string `json:"project_id"`
	TaskID      string `json:"task_id"`
	DependsOnID string `json:"depends_on_id"`
}

func (q *Queries) DeleteDependency(ctx context.Context, arg DeleteDependencyParams) (Dependency, error) {
	row := q.db.QueryRow(ctx, deleteDependency, arg.ProjectID, arg.TaskID, arg.DependsOnID)
	var i Dependency
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.TaskID,
		&i.DependsOnID,
		&i.CreatedAt,
	)
	return i, err
}

const getDependency = `-- name: GetDependency :one
SELECT id, workspace_id, project_id, task_id, depends_on_id, created_at
FROM dependencies
WHERE project_id = $1 AND task_id = $2 AND depends_on_id = $3
LIMIT 1
`

type GetDependencyParams struct {
	ProjectID   string `json:"project_id"`
	TaskID      string `json:"task_id"`
	DependsOnID string `json:"depends_on_id"`
}

func (q *Queries) GetDependency(ctx context.Context, arg GetDependencyParams) (Dependency, error) {
	row := q.db.QueryRow(ctx, getDependency, arg.ProjectID, arg.TaskID, arg.DependsOnID)
	var i Dependency
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.TaskID,
		&i.DependsOnID,
		&i.CreatedAt,
	)
	return i, err
}

const listDependencies = `-- name: ListDependencies :many
SELECT id, workspace_id, project_id, task_id, depends_on_id, created_at
FROM dependencies
WHERE project_id = $1 AND task_id = $2
ORDER BY created_at ASC, id ASC
`

type ListDependenciesParams struct {
	ProjectID string `json:"project_id"`
	TaskID    string `json:"task_id"`
}

func (q *Queries) ListDependencies(ctx context.Context, arg ListDependenciesParams) ([]Dependency, error) {
	rows, err := q.db.Query(ctx, listDependencies, arg.ProjectID, arg.TaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Dependency{}
	for rows.Next() {
		var i Dependency
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.TaskID,
			&i.DependsOnID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
