// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: epics.sql

package db

import (
	"context"
)

const createEpic = `-- name: CreateEpic :one
INSERT INTO epics (
	id, workspace_id, project_id, assigned_to, created_by, updated_by,
	title, description, priority, status, acceptance_criteria
) VALUES (
	$1, $2, $3,
	NULLIF($4, ''), NULLIF($5, ''), NULL,
	$6, NULLIF($7, ''), $8, 'todo', $9::jsonb
)
RETURNING id, workspace_id, project_id, assigned_to, created_by, updated_by, completed_by,
	title, description, status, priority, acceptance_criteria, completion_evidence,
	completion_summary, completed_at, created_at, updated_at
`

type CreateEpicParams struct {
	ID                 string      `json:"id"`
	WorkspaceID        string      `json:"workspace_id"`
	ProjectID          string      `json:"project_id"`
	AssignedTo         interface{} `json:"assigned_to"`
	CreatedBy          interface{} `json:"created_by"`
	Title              string      `json:"title"`
	Description        interface{} `json:"description"`
	Priority           int32       `json:"priority"`
	AcceptanceCriteria []byte      `json:"acceptance_criteria"`
}

func (q *Queries) CreateEpic(ctx context.Context, arg CreateEpicParams) (Epic, error) {
	row := q.db.QueryRow(ctx, createEpic,
		arg.ID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.AssignedTo,
		arg.CreatedBy,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.AcceptanceCriteria,
	)
	var i Epic
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.AssignedTo,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CompletedBy,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AcceptanceCriteria,
		&i.CompletionEvidence,
		&i.CompletionSummary,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEpic = `-- name: DeleteEpic :one
DELETE FROM epics
WHERE project_id = $1 AND id = $2
RETURNING id, workspace_id, project_id, assigned_to, created_by, updated_by, completed_by,
	title, description, status, priority, acceptance_criteria, completion_evidence,
	completion_summary, completed_at, created_at, updated_at
`

type DeleteEpicParams struct {
	ProjectID string `json:"project_id"`
	EpicID    string `json:"epic_id"`
}

func (q *Queries) DeleteEpic(ctx context.Context, arg DeleteEpicParams) (Epic, error) {
	row := q.db.QueryRow(ctx, deleteEpic, arg.ProjectID, arg.EpicID)
	var i Epic
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.AssignedTo,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CompletedBy,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AcceptanceCriteria,
		&i.CompletionEvidence,
		&i.CompletionSummary,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEpic = `-- name: GetEpic :one
SELECT id, workspace_id, project_id, assigned_to, created_by, updated_by, completed_by,
	title, description, status, priority, acceptance_criteria, completion_evidence,
	completion_summary, completed_at, created_at, updated_at
FROM epics
WHERE project_id = $1 AND id = $2
LIMIT 1
`

type GetEpicParams struct {
	ProjectID string `json:"project_id"`
	EpicID    string `json:"epic_id"`
}

func (q *Queries) GetEpic(ctx context.Context, arg GetEpicParams) (Epic, error) {
	row := q.db.QueryRow(ctx, getEpic, arg.ProjectID, arg.EpicID)
	var i Epic
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.AssignedTo,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CompletedBy,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AcceptanceCriteria,
		&i.CompletionEvidence,
		&i.CompletionSummary,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEpics = `-- name: ListEpics :many
SELECT id, workspace_id, project_id, assigned_to, created_by, updated_by, completed_by,
	title, description, status, priority, acceptance_criteria, completion_evidence,
	completion_summary, completed_at, created_at, updated_at
FROM epics
WHERE project_id = $1
  AND ($2 = '' OR status = $2)
ORDER BY priority ASC, created_at ASC, id ASC
`

type ListEpicsParams struct {
	ProjectID string      `json:"project_id"`
	Status    interface{} `json:"status"`
}

func (q *Queries) ListEpics(ctx context.Context, arg ListEpicsParams) ([]Epic, error) {
	rows, err := q.db.Query(ctx, listEpics, arg.ProjectID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Epic{}
	for rows.Next() {
		var i Epic
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.AssignedTo,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CompletedBy,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.AcceptanceCriteria,
			&i.CompletionEvidence,
			&i.CompletionSummary,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextEpicCounter = `-- name: NextEpicCounter :one
WITH project_row AS (
	SELECT workspace_id
	FROM projects
	WHERE id = $1
), upserted AS (
	INSERT INTO id_counters (workspace_id, project_id, entity_type, counter)
	SELECT workspace_id, $1, 'epic', 1
	FROM project_row
	ON CONFLICT (project_id, entity_type) DO UPDATE
	SET counter = id_counters.counter + 1
	RETURNING counter
)
SELECT counter FROM upserted
`

func (q *Queries) NextEpicCounter(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRow(ctx, nextEpicCounter, projectID)
	var counter int64
	err := row.Scan(&counter)
	return counter, err
}

const updateEpic = `-- name: UpdateEpic :one
UPDATE epics
SET updated_by = $1,
	updated_at = now(),
	title = COALESCE($2, title),
	description = COALESCE($3, description),
	priority = COALESCE($4, priority),
	status = COALESCE($5, status),
	assigned_to = COALESCE($6, assigned_to),
	acceptance_criteria = COALESCE($7::jsonb, acceptance_criteria),
	completion_summary = COALESCE($8, completion_summary),
	completion_evidence = COALESCE($9::jsonb, completion_evidence),
	completed_by = CASE
		WHEN COALESCE($5, '') = 'completed' THEN COALESCE(NULLIF($1, ''), completed_by)
		ELSE completed_by
	END,
	completed_at = CASE
		WHEN COALESCE($5, '') = 'completed' THEN COALESCE(completed_at, now())
		ELSE completed_at
	END
WHERE project_id = $10 AND id = $11
RETURNING id, workspace_id, project_id, assigned_to, created_by, updated_by, completed_by,
	title, description, status, priority, acceptance_criteria, completion_evidence,
	completion_summary, completed_at, created_at, updated_at
`

type UpdateEpicParams struct {
	UpdatedBy          *string `json:"updated_by"`
	Title              *string `json:"title"`
	Description        *string `json:"description"`
	Priority           *int32  `json:"priority"`
	Status             *string `json:"status"`
	AssignedTo         *string `json:"assigned_to"`
	AcceptanceCriteria []byte  `json:"acceptance_criteria"`
	CompletionSummary  *string `json:"completion_summary"`
	CompletionEvidence []byte  `json:"completion_evidence"`
	ProjectID          string  `json:"project_id"`
	EpicID             string  `json:"epic_id"`
}

func (q *Queries) UpdateEpic(ctx context.Context, arg UpdateEpicParams) (Epic, error) {
	row := q.db.QueryRow(ctx, updateEpic,
		arg.UpdatedBy,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.Status,
		arg.AssignedTo,
		arg.AcceptanceCriteria,
		arg.CompletionSummary,
		arg.CompletionEvidence,
		arg.ProjectID,
		arg.EpicID,
	)
	var i Epic
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.AssignedTo,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CompletedBy,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AcceptanceCriteria,
		&i.CompletionEvidence,
		&i.CompletionSummary,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
