// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: locks.sql

package db

import (
	"context"
	"time"
)

const createWorkItemLock = `-- name: CreateWorkItemLock :one
INSERT INTO work_item_locks (
	id, workspace_id, project_id, entity_type, entity_id,
	locked_by, reason, expires_at
) VALUES (
	$1, $2, $3, $4, $5,
	$6, NULLIF($7, ''), $8
)
RETURNING id, workspace_id, project_id, entity_type, entity_id, locked_by, reason, leased_at, expires_at, released_at
`

type CreateWorkItemLockParams struct {
	ID          string      `json:"id"`
	WorkspaceID string      `json:"workspace_id"`
	ProjectID   string      `json:"project_id"`
	EntityType  string      `json:"entity_type"`
	EntityID    string      `json:"entity_id"`
	LockedBy    string      `json:"locked_by"`
	Reason      interface{} `json:"reason"`
	ExpiresAt   time.Time   `json:"expires_at"`
}

func (q *Queries) CreateWorkItemLock(ctx context.Context, arg CreateWorkItemLockParams) (WorkItemLock, error) {
	row := q.db.QueryRow(ctx, createWorkItemLock,
		arg.ID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.EntityType,
		arg.EntityID,
		arg.LockedBy,
		arg.Reason,
		arg.ExpiresAt,
	)
	var i WorkItemLock
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.EntityType,
		&i.EntityID,
		&i.LockedBy,
		&i.Reason,
		&i.LeasedAt,
		&i.ExpiresAt,
		&i.ReleasedAt,
	)
	return i, err
}

const getActiveWorkItemLock = `-- name: GetActiveWorkItemLock :one
SELECT id, workspace_id, project_id, entity_type, entity_id, locked_by, reason, leased_at, expires_at, released_at
FROM work_item_locks
WHERE project_id = $1
  AND entity_type = $2
  AND entity_id = $3
  AND released_at IS NULL
  AND expires_at > now()
LIMIT 1
`

type GetActiveWorkItemLockParams struct {
	ProjectID  string `json:"project_id"`
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
}

func (q *Queries) GetActiveWorkItemLock(ctx context.Context, arg GetActiveWorkItemLockParams) (WorkItemLock, error) {
	row := q.db.QueryRow(ctx, getActiveWorkItemLock, arg.ProjectID, arg.EntityType, arg.EntityID)
	var i WorkItemLock
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.EntityType,
		&i.EntityID,
		&i.LockedBy,
		&i.Reason,
		&i.LeasedAt,
		&i.ExpiresAt,
		&i.ReleasedAt,
	)
	return i, err
}

const getWorkItemLock = `-- name: GetWorkItemLock :one
SELECT id, workspace_id, project_id, entity_type, entity_id, locked_by, reason, leased_at, expires_at, released_at
FROM work_item_locks
WHERE project_id = $1 AND id = $2
LIMIT 1
`

type GetWorkItemLockParams struct {
	ProjectID string `json:"project_id"`
	LockID    string `json:"lock_id"`
}

func (q *Queries) GetWorkItemLock(ctx context.Context, arg GetWorkItemLockParams) (WorkItemLock, error) {
	row := q.db.QueryRow(ctx, getWorkItemLock, arg.ProjectID, arg.LockID)
	var i WorkItemLock
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.EntityType,
		&i.EntityID,
		&i.LockedBy,
		&i.Reason,
		&i.LeasedAt,
		&i.ExpiresAt,
		&i.ReleasedAt,
	)
	return i, err
}

const listWorkItemLocks = `-- name: ListWorkItemLocks :many
SELECT id, workspace_id, project_id, entity_type, entity_id, locked_by, reason, leased_at, expires_at, released_at
FROM work_item_locks
WHERE project_id = $1
  AND (COALESCE(array_length($2::text[], 1), 0) = 0 OR entity_type = ANY($2::text[]))
  AND ($3 = '' OR entity_id = $3)
  AND (NOT $4::bool OR (released_at IS NULL AND expires_at > now()))
ORDER BY leased_at DESC, id DESC
`

type ListWorkItemLocksParams struct {
	ProjectID   string      `json:"project_id"`
	EntityTypes []string    `json:"entity_types"`
	EntityID    interface{} `json:"entity_id"`
	Active      bool        `json:"active"`
}

func (q *Queries) ListWorkItemLocks(ctx context.Context, arg ListWorkItemLocksParams) ([]WorkItemLock, error) {
	rows, err := q.db.Query(ctx, listWorkItemLocks,
		arg.ProjectID,
		arg.EntityTypes,
		arg.EntityID,
		arg.Active,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkItemLock{}
	for rows.Next() {
		var i WorkItemLock
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.EntityType,
			&i.EntityID,
			&i.LockedBy,
			&i.Reason,
			&i.LeasedAt,
			&i.ExpiresAt,
			&i.ReleasedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextLockCounter = `-- name: NextLockCounter :one
WITH project_row AS (
	SELECT workspace_id
	FROM projects
	WHERE id = $1
), upserted AS (
	INSERT INTO id_counters (workspace_id, project_id, entity_type, counter)
	SELECT workspace_id, $1, 'lock', 1
	FROM project_row
	ON CONFLICT (project_id, entity_type) DO UPDATE
	SET counter = id_counters.counter + 1
	RETURNING counter
)
SELECT counter FROM upserted
`

func (q *Queries) NextLockCounter(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRow(ctx, nextLockCounter, projectID)
	var counter int64
	err := row.Scan(&counter)
	return counter, err
}

const releaseExpiredWorkItemLock = `-- name: ReleaseExpiredWorkItemLock :exec
UPDATE work_item_locks
SET released_at = now()
WHERE project_id = $1
  AND entity_type = $2
  AND entity_id = $3
  AND released_at IS NULL
  AND expires_at <= now()
`

type ReleaseExpiredWorkItemLockParams struct {
	ProjectID  string `json:"project_id"`
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
}

func (q *Queries) ReleaseExpiredWorkItemLock(ctx context.Context, arg ReleaseExpiredWorkItemLockParams) error {
	_, err := q.db.Exec(ctx, releaseExpiredWorkItemLock, arg.ProjectID, arg.EntityType, arg.EntityID)
	return err
}

const releaseWorkItemLock = `-- name: ReleaseWorkItemLock :one
UPDATE work_item_locks
SET released_at = COALESCE(released_at, now())
WHERE project_id = $1 AND id = $2
RETURNING id, workspace_id, project_id, entity_type, entity_id, locked_by, reason, leased_at, expires_at, released_at
`

type ReleaseWorkItemLockParams struct {
	ProjectID string `json:"project_id"`
	LockID    string `json:"lock_id"`
}

func (q *Queries) ReleaseWorkItemLock(ctx context.Context, arg ReleaseWorkItemLockParams) (WorkItemLock, error) {
	row := q.db.QueryRow(ctx, releaseWorkItemLock, arg.ProjectID, arg.LockID)
	var i WorkItemLock
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.EntityType,
		&i.EntityID,
		&i.LockedBy,
		&i.Reason,
		&i.LeasedAt,
		&i.ExpiresAt,
		&i.ReleasedAt,
	)
	return i, err
}
