// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	ID           string    `json:"id"`
	WorkspaceID  string    `json:"workspace_id"`
	ProjectID    string    `json:"project_id"`
	TaskID       string    `json:"task_id"`
	AuthorUserID *string   `json:"author_user_id"`
	Author       string    `json:"author"`
	Kind         string    `json:"kind"`
	Content      string    `json:"content"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Dependency struct {
	ID          string    `json:"id"`
	WorkspaceID string    `json:"workspace_id"`
	ProjectID   string    `json:"project_id"`
	TaskID      string    `json:"task_id"`
	DependsOnID string    `json:"depends_on_id"`
	CreatedAt   time.Time `json:"created_at"`
}

type Epic struct {
	ID                 string             `json:"id"`
	WorkspaceID        string             `json:"workspace_id"`
	ProjectID          string             `json:"project_id"`
	AssignedTo         *string            `json:"assigned_to"`
	CreatedBy          *string            `json:"created_by"`
	UpdatedBy          *string            `json:"updated_by"`
	CompletedBy        *string            `json:"completed_by"`
	Title              string             `json:"title"`
	Description        *string            `json:"description"`
	Status             string             `json:"status"`
	Priority           int32              `json:"priority"`
	AcceptanceCriteria []byte             `json:"acceptance_criteria"`
	CompletionEvidence []byte             `json:"completion_evidence"`
	CompletionSummary  *string            `json:"completion_summary"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
}

type Event struct {
	ID          int64     `json:"id"`
	WorkspaceID string    `json:"workspace_id"`
	ProjectID   string    `json:"project_id"`
	Action      string    `json:"action"`
	EntityType  string    `json:"entity_type"`
	EntityID    string    `json:"entity_id"`
	ActorUserID *string   `json:"actor_user_id"`
	ActorLabel  *string   `json:"actor_label"`
	BeforeState []byte    `json:"before_state"`
	AfterState  []byte    `json:"after_state"`
	Metadata    []byte    `json:"metadata"`
	CreatedAt   time.Time `json:"created_at"`
}

type IDCounter struct {
	WorkspaceID string `json:"workspace_id"`
	ProjectID   string `json:"project_id"`
	EntityType  string `json:"entity_type"`
	Counter     int64  `json:"counter"`
}

type Project struct {
	ID          string    `json:"id"`
	WorkspaceID string    `json:"workspace_id"`
	Name        string    `json:"name"`
	IssuePrefix *string   `json:"issue_prefix"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type ProjectConfig struct {
	WorkspaceID string    `json:"workspace_id"`
	ProjectID   string    `json:"project_id"`
	Key         string    `json:"key"`
	Value       string    `json:"value"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type SearchIndex struct {
	ID          int64       `json:"id"`
	WorkspaceID string      `json:"workspace_id"`
	ProjectID   string      `json:"project_id"`
	EntityID    string      `json:"entity_id"`
	EntityType  string      `json:"entity_type"`
	Title       string      `json:"title"`
	Content     string      `json:"content"`
	Author      string      `json:"author"`
	Status      string      `json:"status"`
	ParentID    *string     `json:"parent_id"`
	Document    interface{} `json:"document"`
}

type Task struct {
	ID                 string             `json:"id"`
	WorkspaceID        string             `json:"workspace_id"`
	ProjectID          string             `json:"project_id"`
	EpicID             *string            `json:"epic_id"`
	ParentTaskID       *string            `json:"parent_task_id"`
	AssignedTo         *string            `json:"assigned_to"`
	CreatedBy          *string            `json:"created_by"`
	UpdatedBy          *string            `json:"updated_by"`
	CompletedBy        *string            `json:"completed_by"`
	Title              string             `json:"title"`
	Description        *string            `json:"description"`
	Priority           int32              `json:"priority"`
	Status             string             `json:"status"`
	Tags               []string           `json:"tags"`
	AcceptanceCriteria []byte             `json:"acceptance_criteria"`
	CompletionEvidence []byte             `json:"completion_evidence"`
	CompletionSummary  *string            `json:"completion_summary"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
}

type User struct {
	ID               string             `json:"id"`
	DisplayName      string             `json:"display_name"`
	Role             string             `json:"role"`
	AccessKey        string             `json:"access_key"`
	AccessSecretHash string             `json:"access_secret_hash"`
	Username         *string            `json:"username"`
	PasswordHash     *string            `json:"password_hash"`
	DisabledAt       pgtype.Timestamptz `json:"disabled_at"`
	LastSeenAt       pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
}

type UserProjectAccess struct {
	UserID      string    `json:"user_id"`
	WorkspaceID string    `json:"workspace_id"`
	ProjectID   string    `json:"project_id"`
	CreatedAt   time.Time `json:"created_at"`
}

type WorkItemLock struct {
	ID          string             `json:"id"`
	WorkspaceID string             `json:"workspace_id"`
	ProjectID   string             `json:"project_id"`
	EntityType  string             `json:"entity_type"`
	EntityID    string             `json:"entity_id"`
	LockedBy    string             `json:"locked_by"`
	Reason      *string            `json:"reason"`
	LeasedAt    time.Time          `json:"leased_at"`
	ExpiresAt   time.Time          `json:"expires_at"`
	ReleasedAt  pgtype.Timestamptz `json:"released_at"`
}

type Workspace struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
