// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_config.sql

package db

import (
	"context"
)

const deleteProjectConfig = `-- name: DeleteProjectConfig :one
DELETE FROM project_config
WHERE project_id = $1 AND key = $2
RETURNING key, value
`

type DeleteProjectConfigParams struct {
	ProjectID string `json:"project_id"`
	Key       string `json:"key"`
}

type DeleteProjectConfigRow struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) DeleteProjectConfig(ctx context.Context, arg DeleteProjectConfigParams) (DeleteProjectConfigRow, error) {
	row := q.db.QueryRow(ctx, deleteProjectConfig, arg.ProjectID, arg.Key)
	var i DeleteProjectConfigRow
	err := row.Scan(&i.Key, &i.Value)
	return i, err
}

const getProjectConfig = `-- name: GetProjectConfig :one
SELECT key, value
FROM project_config
WHERE project_id = $1 AND key = $2
`

type GetProjectConfigParams struct {
	ProjectID string `json:"project_id"`
	Key       string `json:"key"`
}

type GetProjectConfigRow struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) GetProjectConfig(ctx context.Context, arg GetProjectConfigParams) (GetProjectConfigRow, error) {
	row := q.db.QueryRow(ctx, getProjectConfig, arg.ProjectID, arg.Key)
	var i GetProjectConfigRow
	err := row.Scan(&i.Key, &i.Value)
	return i, err
}

const listProjectConfig = `-- name: ListProjectConfig :many
SELECT key, value
FROM project_config
WHERE project_id = $1
ORDER BY key
`

type ListProjectConfigRow struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) ListProjectConfig(ctx context.Context, projectID string) ([]ListProjectConfigRow, error) {
	rows, err := q.db.Query(ctx, listProjectConfig, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectConfigRow{}
	for rows.Next() {
		var i ListProjectConfigRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProjectConfig = `-- name: SetProjectConfig :one
WITH project_row AS (
	SELECT workspace_id
	FROM projects
	WHERE id = $1
), upserted AS (
	INSERT INTO project_config (
		workspace_id, project_id, key, value
	)
	SELECT workspace_id, $1, $2, $3
	FROM project_row
	ON CONFLICT (project_id, key) DO UPDATE
	SET value = EXCLUDED.value,
		updated_at = now()
	RETURNING key, value
)
SELECT key, value FROM upserted
`

type SetProjectConfigParams struct {
	ProjectID string `json:"project_id"`
	Key       string `json:"key"`
	Value     string `json:"value"`
}

type SetProjectConfigRow struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) SetProjectConfig(ctx context.Context, arg SetProjectConfigParams) (SetProjectConfigRow, error) {
	row := q.db.QueryRow(ctx, setProjectConfig, arg.ProjectID, arg.Key, arg.Value)
	var i SetProjectConfigRow
	err := row.Scan(&i.Key, &i.Value)
	return i, err
}
