// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CountAdminUsers(ctx context.Context) (int64, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateDependency(ctx context.Context, arg CreateDependencyParams) (Dependency, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (string, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (CreateTaskRow, error)
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (string, error)
	DeleteComment(ctx context.Context, arg DeleteCommentParams) (Comment, error)
	DeleteDependency(ctx context.Context, arg DeleteDependencyParams) (Dependency, error)
	DeleteProjectConfig(ctx context.Context, arg DeleteProjectConfigParams) (DeleteProjectConfigRow, error)
	DeleteTask(ctx context.Context, arg DeleteTaskParams) (Task, error)
	GetComment(ctx context.Context, arg GetCommentParams) (Comment, error)
	GetDependency(ctx context.Context, arg GetDependencyParams) (Dependency, error)
	GetEpicID(ctx context.Context, arg GetEpicIDParams) (string, error)
	GetProjectConfig(ctx context.Context, arg GetProjectConfigParams) (GetProjectConfigRow, error)
	GetProjectIDByWorkspaceAndName(ctx context.Context, arg GetProjectIDByWorkspaceAndNameParams) (string, error)
	GetProjectWorkspaceID(ctx context.Context, projectID string) (string, error)
	GetTaskCreateParentInfo(ctx context.Context, arg GetTaskCreateParentInfoParams) (GetTaskCreateParentInfoRow, error)
	GetTaskDetail(ctx context.Context, arg GetTaskDetailParams) (Task, error)
	GetUserID(ctx context.Context, userID string) (string, error)
	GetWorkspaceIDBySlug(ctx context.Context, slug string) (string, error)
	HistoryEvents(ctx context.Context, arg HistoryEventsParams) ([]Event, error)
	InsertAdminUser(ctx context.Context, arg InsertAdminUserParams) error
	InsertBootstrapUser(ctx context.Context, arg InsertBootstrapUserParams) error
	InsertEvent(ctx context.Context, arg InsertEventParams) error
	InsertUserProjectAccess(ctx context.Context, arg InsertUserProjectAccessParams) error
	ListComments(ctx context.Context, arg ListCommentsParams) ([]Comment, error)
	ListDependencies(ctx context.Context, arg ListDependenciesParams) ([]Dependency, error)
	ListEpics(ctx context.Context, arg ListEpicsParams) ([]ListEpicsRow, error)
	ListProjectConfig(ctx context.Context, projectID string) ([]ListProjectConfigRow, error)
	ListReadyDependents(ctx context.Context, arg ListReadyDependentsParams) ([]ListReadyDependentsRow, error)
	ListReadyTasks(ctx context.Context, arg ListReadyTasksParams) ([]ListReadyTasksRow, error)
	ListSubtasks(ctx context.Context, arg ListSubtasksParams) ([]ListSubtasksRow, error)
	ListTasks(ctx context.Context, arg ListTasksParams) ([]ListTasksRow, error)
	ListTasksUnified(ctx context.Context, arg ListTasksUnifiedParams) ([]ListTasksUnifiedRow, error)
	LockUsersTable(ctx context.Context) error
	LookupAdminByUsername(ctx context.Context, username *string) (LookupAdminByUsernameRow, error)
	NextTaskCounter(ctx context.Context, projectID string) (int64, error)
	SearchComments(ctx context.Context, arg SearchCommentsParams) ([]SearchCommentsRow, error)
	SearchEpics(ctx context.Context, arg SearchEpicsParams) ([]SearchEpicsRow, error)
	SearchTasks(ctx context.Context, arg SearchTasksParams) ([]SearchTasksRow, error)
	SetProjectConfig(ctx context.Context, arg SetProjectConfigParams) (SetProjectConfigRow, error)
	UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
}

var _ Querier = (*Queries)(nil)
