// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
	id, workspace_id, project_id, epic_id, parent_task_id, assigned_to,
	created_by, updated_by, title, description, kind, root_cause_analysis, priority,
	status, tags, planned_files, acceptance_criteria
) VALUES (
	$1, $2, $3, NULLIF($4, ''),
	NULLIF($5, ''), NULLIF($6, ''),
	NULLIF($7, ''), NULL, $8, NULLIF($9, ''), $10, $11, $12,
	'todo', $13, $14::jsonb, $15::jsonb
)
RETURNING id, title, status, priority, project_id, workspace_id, kind, root_cause_analysis, planned_files
`

type CreateTaskParams struct {
	ID                 string      `json:"id"`
	WorkspaceID        string      `json:"workspace_id"`
	ProjectID          string      `json:"project_id"`
	EpicID             interface{} `json:"epic_id"`
	ParentTaskID       interface{} `json:"parent_task_id"`
	AssignedTo         interface{} `json:"assigned_to"`
	CreatedBy          interface{} `json:"created_by"`
	Title              string      `json:"title"`
	Description        interface{} `json:"description"`
	Kind               string      `json:"kind"`
	RootCauseAnalysis  string      `json:"root_cause_analysis"`
	Priority           int32       `json:"priority"`
	Tags               []string    `json:"tags"`
	PlannedFiles       []byte      `json:"planned_files"`
	AcceptanceCriteria []byte      `json:"acceptance_criteria"`
}

type CreateTaskRow struct {
	ID                string `json:"id"`
	Title             string `json:"title"`
	Status            string `json:"status"`
	Priority          int32  `json:"priority"`
	ProjectID         string `json:"project_id"`
	WorkspaceID       string `json:"workspace_id"`
	Kind              string `json:"kind"`
	RootCauseAnalysis string `json:"root_cause_analysis"`
	PlannedFiles      []byte `json:"planned_files"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (CreateTaskRow, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.EpicID,
		arg.ParentTaskID,
		arg.AssignedTo,
		arg.CreatedBy,
		arg.Title,
		arg.Description,
		arg.Kind,
		arg.RootCauseAnalysis,
		arg.Priority,
		arg.Tags,
		arg.PlannedFiles,
		arg.AcceptanceCriteria,
	)
	var i CreateTaskRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.Priority,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.Kind,
		&i.RootCauseAnalysis,
		&i.PlannedFiles,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :one
DELETE FROM tasks
WHERE project_id = $1 AND id = $2
RETURNING id, workspace_id, project_id, epic_id, parent_task_id, kind, root_cause_analysis, assigned_to,
	created_by, updated_by, completed_by, title, description, priority,
	status, tags, planned_files, changed_files, acceptance_criteria, completion_evidence, completion_summary,
	completed_at, created_at, updated_at
`

type DeleteTaskParams struct {
	ProjectID string `json:"project_id"`
	TaskID    string `json:"task_id"`
}

type DeleteTaskRow struct {
	ID                 string             `json:"id"`
	WorkspaceID        string             `json:"workspace_id"`
	ProjectID          string             `json:"project_id"`
	EpicID             *string            `json:"epic_id"`
	ParentTaskID       *string            `json:"parent_task_id"`
	Kind               string             `json:"kind"`
	RootCauseAnalysis  string             `json:"root_cause_analysis"`
	AssignedTo         *string            `json:"assigned_to"`
	CreatedBy          *string            `json:"created_by"`
	UpdatedBy          *string            `json:"updated_by"`
	CompletedBy        *string            `json:"completed_by"`
	Title              string             `json:"title"`
	Description        *string            `json:"description"`
	Priority           int32              `json:"priority"`
	Status             string             `json:"status"`
	Tags               []string           `json:"tags"`
	PlannedFiles       []byte             `json:"planned_files"`
	ChangedFiles       []byte             `json:"changed_files"`
	AcceptanceCriteria []byte             `json:"acceptance_criteria"`
	CompletionEvidence []byte             `json:"completion_evidence"`
	CompletionSummary  *string            `json:"completion_summary"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) (DeleteTaskRow, error) {
	row := q.db.QueryRow(ctx, deleteTask, arg.ProjectID, arg.TaskID)
	var i DeleteTaskRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.EpicID,
		&i.ParentTaskID,
		&i.Kind,
		&i.RootCauseAnalysis,
		&i.AssignedTo,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CompletedBy,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.Tags,
		&i.PlannedFiles,
		&i.ChangedFiles,
		&i.AcceptanceCriteria,
		&i.CompletionEvidence,
		&i.CompletionSummary,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEpicID = `-- name: GetEpicID :one
SELECT id
FROM epics
WHERE project_id = $1 AND id = $2
LIMIT 1
`

type GetEpicIDParams struct {
	ProjectID string `json:"project_id"`
	EpicID    string `json:"epic_id"`
}

func (q *Queries) GetEpicID(ctx context.Context, arg GetEpicIDParams) (string, error) {
	row := q.db.QueryRow(ctx, getEpicID, arg.ProjectID, arg.EpicID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getProjectWorkspaceID = `-- name: GetProjectWorkspaceID :one
SELECT workspace_id
FROM projects
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetProjectWorkspaceID(ctx context.Context, projectID string) (string, error) {
	row := q.db.QueryRow(ctx, getProjectWorkspaceID, projectID)
	var workspace_id string
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const getTaskCreateParentInfo = `-- name: GetTaskCreateParentInfo :one
SELECT id, epic_id, parent_task_id
FROM tasks
WHERE project_id = $1 AND id = $2
LIMIT 1
`

type GetTaskCreateParentInfoParams struct {
	ProjectID string `json:"project_id"`
	TaskID    string `json:"task_id"`
}

type GetTaskCreateParentInfoRow struct {
	ID           string  `json:"id"`
	EpicID       *string `json:"epic_id"`
	ParentTaskID *string `json:"parent_task_id"`
}

func (q *Queries) GetTaskCreateParentInfo(ctx context.Context, arg GetTaskCreateParentInfoParams) (GetTaskCreateParentInfoRow, error) {
	row := q.db.QueryRow(ctx, getTaskCreateParentInfo, arg.ProjectID, arg.TaskID)
	var i GetTaskCreateParentInfoRow
	err := row.Scan(&i.ID, &i.EpicID, &i.ParentTaskID)
	return i, err
}

const getTaskDetail = `-- name: GetTaskDetail :one
SELECT id, workspace_id, project_id, epic_id, parent_task_id, assigned_to,
	created_by, updated_by, completed_by, title, description, kind, root_cause_analysis, priority,
	status, tags, planned_files, changed_files, acceptance_criteria, completion_evidence, completion_summary,
	completed_at, created_at, updated_at
FROM tasks
WHERE project_id = $1 AND id = $2
`

type GetTaskDetailParams struct {
	ProjectID string `json:"project_id"`
	TaskID    string `json:"task_id"`
}

type GetTaskDetailRow struct {
	ID                 string             `json:"id"`
	WorkspaceID        string             `json:"workspace_id"`
	ProjectID          string             `json:"project_id"`
	EpicID             *string            `json:"epic_id"`
	ParentTaskID       *string            `json:"parent_task_id"`
	AssignedTo         *string            `json:"assigned_to"`
	CreatedBy          *string            `json:"created_by"`
	UpdatedBy          *string            `json:"updated_by"`
	CompletedBy        *string            `json:"completed_by"`
	Title              string             `json:"title"`
	Description        *string            `json:"description"`
	Kind               string             `json:"kind"`
	RootCauseAnalysis  string             `json:"root_cause_analysis"`
	Priority           int32              `json:"priority"`
	Status             string             `json:"status"`
	Tags               []string           `json:"tags"`
	PlannedFiles       []byte             `json:"planned_files"`
	ChangedFiles       []byte             `json:"changed_files"`
	AcceptanceCriteria []byte             `json:"acceptance_criteria"`
	CompletionEvidence []byte             `json:"completion_evidence"`
	CompletionSummary  *string            `json:"completion_summary"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
}

func (q *Queries) GetTaskDetail(ctx context.Context, arg GetTaskDetailParams) (GetTaskDetailRow, error) {
	row := q.db.QueryRow(ctx, getTaskDetail, arg.ProjectID, arg.TaskID)
	var i GetTaskDetailRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.EpicID,
		&i.ParentTaskID,
		&i.AssignedTo,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CompletedBy,
		&i.Title,
		&i.Description,
		&i.Kind,
		&i.RootCauseAnalysis,
		&i.Priority,
		&i.Status,
		&i.Tags,
		&i.PlannedFiles,
		&i.ChangedFiles,
		&i.AcceptanceCriteria,
		&i.CompletionEvidence,
		&i.CompletionSummary,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserID = `-- name: GetUserID :one
SELECT id
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserID(ctx context.Context, userID string) (string, error) {
	row := q.db.QueryRow(ctx, getUserID, userID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const listReadyDependents = `-- name: ListReadyDependents :many
SELECT d.depends_on_id, t.id, t.title, t.status, t.priority, t.epic_id, t.parent_task_id, t.tags
FROM dependencies d
JOIN tasks t ON t.project_id = d.project_id AND t.id = d.task_id
WHERE d.project_id = $1
  AND d.depends_on_id = ANY($2::text[])
  AND t.parent_task_id IS NULL
  AND t.status = 'todo'
  AND ($3 = '' OR t.epic_id = $3)
  AND NOT EXISTS (
	SELECT 1
	FROM dependencies d2
	JOIN tasks dep ON dep.project_id = d2.project_id AND dep.id = d2.depends_on_id
	WHERE d2.project_id = t.project_id
	  AND d2.task_id = t.id
	  AND dep.status NOT IN ('completed', 'wont_fix', 'archived')
  )
ORDER BY t.priority ASC, t.created_at ASC, t.id ASC
`

type ListReadyDependentsParams struct {
	ProjectID string      `json:"project_id"`
	ReadyIds  []string    `json:"ready_ids"`
	EpicID    interface{} `json:"epic_id"`
}

type ListReadyDependentsRow struct {
	DependsOnID  string   `json:"depends_on_id"`
	ID           string   `json:"id"`
	Title        string   `json:"title"`
	Status       string   `json:"status"`
	Priority     int32    `json:"priority"`
	EpicID       *string  `json:"epic_id"`
	ParentTaskID *string  `json:"parent_task_id"`
	Tags         []string `json:"tags"`
}

func (q *Queries) ListReadyDependents(ctx context.Context, arg ListReadyDependentsParams) ([]ListReadyDependentsRow, error) {
	rows, err := q.db.Query(ctx, listReadyDependents, arg.ProjectID, arg.ReadyIds, arg.EpicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReadyDependentsRow{}
	for rows.Next() {
		var i ListReadyDependentsRow
		if err := rows.Scan(
			&i.DependsOnID,
			&i.ID,
			&i.Title,
			&i.Status,
			&i.Priority,
			&i.EpicID,
			&i.ParentTaskID,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadyTasks = `-- name: ListReadyTasks :many
SELECT id, title, description, status, priority, epic_id, parent_task_id, tags
FROM tasks t
WHERE t.project_id = $1
  AND t.parent_task_id IS NULL
  AND t.status = 'todo'
  AND ($2 = '' OR t.epic_id = $2)
  AND NOT EXISTS (
	SELECT 1
	FROM dependencies d
	JOIN tasks dep ON dep.project_id = d.project_id AND dep.id = d.depends_on_id
	WHERE d.project_id = t.project_id
	  AND d.task_id = t.id
	  AND dep.status NOT IN ('completed', 'wont_fix', 'archived')
  )
ORDER BY t.priority ASC, t.created_at ASC, t.id ASC
`

type ListReadyTasksParams struct {
	ProjectID string      `json:"project_id"`
	EpicID    interface{} `json:"epic_id"`
}

type ListReadyTasksRow struct {
	ID           string   `json:"id"`
	Title        string   `json:"title"`
	Description  *string  `json:"description"`
	Status       string   `json:"status"`
	Priority     int32    `json:"priority"`
	EpicID       *string  `json:"epic_id"`
	ParentTaskID *string  `json:"parent_task_id"`
	Tags         []string `json:"tags"`
}

func (q *Queries) ListReadyTasks(ctx context.Context, arg ListReadyTasksParams) ([]ListReadyTasksRow, error) {
	rows, err := q.db.Query(ctx, listReadyTasks, arg.ProjectID, arg.EpicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReadyTasksRow{}
	for rows.Next() {
		var i ListReadyTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.EpicID,
			&i.ParentTaskID,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubtasks = `-- name: ListSubtasks :many
SELECT id, title, status, priority, kind, epic_id, parent_task_id, tags, created_at, updated_at
FROM tasks
WHERE project_id = $1
  AND parent_task_id = $2
  AND ($3 = '' OR status = $3)
ORDER BY priority ASC, created_at ASC, id ASC
`

type ListSubtasksParams struct {
	ProjectID    string      `json:"project_id"`
	ParentTaskID *string     `json:"parent_task_id"`
	Status       interface{} `json:"status"`
}

type ListSubtasksRow struct {
	ID           string    `json:"id"`
	Title        string    `json:"title"`
	Status       string    `json:"status"`
	Priority     int32     `json:"priority"`
	Kind         string    `json:"kind"`
	EpicID       *string   `json:"epic_id"`
	ParentTaskID *string   `json:"parent_task_id"`
	Tags         []string  `json:"tags"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) ListSubtasks(ctx context.Context, arg ListSubtasksParams) ([]ListSubtasksRow, error) {
	rows, err := q.db.Query(ctx, listSubtasks, arg.ProjectID, arg.ParentTaskID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubtasksRow{}
	for rows.Next() {
		var i ListSubtasksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.Priority,
			&i.Kind,
			&i.EpicID,
			&i.ParentTaskID,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, title, status, priority, kind, epic_id, parent_task_id, tags, created_at, updated_at
FROM tasks
WHERE project_id = $1
  AND parent_task_id IS NULL
  AND ($2 = '' OR status = $2)
  AND ($3 = '' OR epic_id = $3)
ORDER BY priority ASC, created_at ASC, id ASC
`

type ListTasksParams struct {
	ProjectID string      `json:"project_id"`
	Status    interface{} `json:"status"`
	EpicID    interface{} `json:"epic_id"`
}

type ListTasksRow struct {
	ID           string    `json:"id"`
	Title        string    `json:"title"`
	Status       string    `json:"status"`
	Priority     int32     `json:"priority"`
	Kind         string    `json:"kind"`
	EpicID       *string   `json:"epic_id"`
	ParentTaskID *string   `json:"parent_task_id"`
	Tags         []string  `json:"tags"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]ListTasksRow, error) {
	rows, err := q.db.Query(ctx, listTasks, arg.ProjectID, arg.Status, arg.EpicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTasksRow{}
	for rows.Next() {
		var i ListTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.Priority,
			&i.Kind,
			&i.EpicID,
			&i.ParentTaskID,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextTaskCounter = `-- name: NextTaskCounter :one
WITH project_row AS (
	SELECT workspace_id
	FROM projects
	WHERE id = $1
), upserted AS (
	INSERT INTO id_counters (workspace_id, project_id, entity_type, counter)
	SELECT workspace_id, $1, 'task', 1
	FROM project_row
	ON CONFLICT (project_id, entity_type) DO UPDATE
	SET counter = id_counters.counter + 1
	RETURNING counter
)
SELECT counter FROM upserted
`

func (q *Queries) NextTaskCounter(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRow(ctx, nextTaskCounter, projectID)
	var counter int64
	err := row.Scan(&counter)
	return counter, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET updated_by = $1,
	updated_at = now(),
	title = COALESCE($2, title),
	description = COALESCE($3, description),
	kind = COALESCE($4, kind),
	root_cause_analysis = COALESCE($5, root_cause_analysis),
	priority = COALESCE($6, priority),
	status = COALESCE($7, status),
	tags = COALESCE($8, tags),
	epic_id = CASE WHEN $9::bool THEN NULL ELSE COALESCE($10, epic_id) END,
	assigned_to = COALESCE($11, assigned_to),
	changed_files = COALESCE($12::jsonb, changed_files),
	acceptance_criteria = COALESCE($13::jsonb, acceptance_criteria),
	completion_summary = COALESCE($14, completion_summary),
	completion_evidence = COALESCE($15::jsonb, completion_evidence),
	completed_by = CASE
		WHEN COALESCE($7, '') = 'completed' THEN COALESCE(NULLIF($1, ''), completed_by)
		ELSE completed_by
	END,
	completed_at = CASE
		WHEN COALESCE($7, '') = 'completed' THEN COALESCE(completed_at, now())
		ELSE completed_at
	END
WHERE project_id = $16 AND id = $17
RETURNING id, workspace_id, project_id, epic_id, parent_task_id, assigned_to,
	created_by, updated_by, completed_by, title, description, kind, root_cause_analysis, priority,
	status, tags, planned_files, changed_files, acceptance_criteria, completion_evidence, completion_summary,
	completed_at, created_at, updated_at
`

type UpdateTaskParams struct {
	UpdatedBy          *string  `json:"updated_by"`
	Title              *string  `json:"title"`
	Description        *string  `json:"description"`
	Kind               *string  `json:"kind"`
	RootCauseAnalysis  *string  `json:"root_cause_analysis"`
	Priority           *int32   `json:"priority"`
	Status             *string  `json:"status"`
	Tags               []string `json:"tags"`
	ClearEpic          bool     `json:"clear_epic"`
	EpicID             *string  `json:"epic_id"`
	AssignedTo         *string  `json:"assigned_to"`
	ChangedFiles       []byte   `json:"changed_files"`
	AcceptanceCriteria []byte   `json:"acceptance_criteria"`
	CompletionSummary  *string  `json:"completion_summary"`
	CompletionEvidence []byte   `json:"completion_evidence"`
	ProjectID          string   `json:"project_id"`
	TaskID             string   `json:"task_id"`
}

type UpdateTaskRow struct {
	ID                 string             `json:"id"`
	WorkspaceID        string             `json:"workspace_id"`
	ProjectID          string             `json:"project_id"`
	EpicID             *string            `json:"epic_id"`
	ParentTaskID       *string            `json:"parent_task_id"`
	AssignedTo         *string            `json:"assigned_to"`
	CreatedBy          *string            `json:"created_by"`
	UpdatedBy          *string            `json:"updated_by"`
	CompletedBy        *string            `json:"completed_by"`
	Title              string             `json:"title"`
	Description        *string            `json:"description"`
	Kind               string             `json:"kind"`
	RootCauseAnalysis  string             `json:"root_cause_analysis"`
	Priority           int32              `json:"priority"`
	Status             string             `json:"status"`
	Tags               []string           `json:"tags"`
	PlannedFiles       []byte             `json:"planned_files"`
	ChangedFiles       []byte             `json:"changed_files"`
	AcceptanceCriteria []byte             `json:"acceptance_criteria"`
	CompletionEvidence []byte             `json:"completion_evidence"`
	CompletionSummary  *string            `json:"completion_summary"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (UpdateTaskRow, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.UpdatedBy,
		arg.Title,
		arg.Description,
		arg.Kind,
		arg.RootCauseAnalysis,
		arg.Priority,
		arg.Status,
		arg.Tags,
		arg.ClearEpic,
		arg.EpicID,
		arg.AssignedTo,
		arg.ChangedFiles,
		arg.AcceptanceCriteria,
		arg.CompletionSummary,
		arg.CompletionEvidence,
		arg.ProjectID,
		arg.TaskID,
	)
	var i UpdateTaskRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.EpicID,
		&i.ParentTaskID,
		&i.AssignedTo,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CompletedBy,
		&i.Title,
		&i.Description,
		&i.Kind,
		&i.RootCauseAnalysis,
		&i.Priority,
		&i.Status,
		&i.Tags,
		&i.PlannedFiles,
		&i.ChangedFiles,
		&i.AcceptanceCriteria,
		&i.CompletionEvidence,
		&i.CompletionSummary,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
